---
 - name: Delete {{ name }} deployment
   shell: "kubectl delete deployment {{ name }} --namespace={{ ns }}"
   ignore_errors: yes

 - name: Wait for {{ name }} pods to be deleted
   shell: "kubectl get pods --namespace={{ ns }}"
   register: result
   until: result.stdout.find(name) == -1
   retries: "{{ retry.max }}"
   delay: "{{ retry.delay }}"

 - name: Wait for {{ name }} deployment to be deleted
   shell: "kubectl get deployments --namespace={{ ns }}"
   register: result
   until: result.stdout.find(name) == -1
   retries: "{{ retry.max }}"
   delay: "{{ retry.delay }}"

 - name: "Create {{ name }} deployment (from file: {{ yamls }}/{{ file }}-deployment.yml)"
   shell: "kubectl create -f {{ yamls }}/{{ file }}-deployment.yml"
